# -*- coding: utf-8 -*-
"""Web Scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19Oidi4YdP4D6_cSl6a_ZHaCNgVpJddfx
"""

from bs4 import BeautifulSoup
import requests

url = 'https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue'

page = requests.get(url)

soup = BeautifulSoup(page.text,'html')

print(soup)

table = soup.find_all('table')[1]

soup.find('table',class_ = 'wikitable sortable jquery-tablesorter')

<table class="wikitable sortable jquery-tablesorter">
<caption>

w_titles = table.find_all('th')

w_titles

world_titles = [title.text.strip() for title in w_titles]

print(world_titles)

import pandas as pd

df = pd.DataFrame(columns = world_titles)
df

c_data = table.find_all('tr')
c_data

for row in c_data[1:]:
  r_data = row.find_all('td')
  ind_r_data = [data.text.strip() for data in r_data]
  length = len(df)
  df.loc[length] = ind_r_data

df

df.to_csv(r'walmart.csv', index = False)